### ISSUE TITLE
Visual feedback not present when sorting huge tables

### ISSUE THREAD

**Issue by umbobabo** [Financial-Times/o-table#136]
Add visual feedback for the user while sorting huge tables to prevent that they think that nothing is happening.

## What

We are implementing o-table with huge tables and has been communicated that is not an unusual scenario in Editorial content.
A table can be 1000 rows and 8 columns for instance.
In such a case, there is a perceivable delay after the click on the sort icon of one of these columns and the paint of the new rendered table in the screen.
This has been tested on a desktop machine with average computational power.

The initial user reaction was that the feature wasn't working.

**Comment by JakeChampion** [comment]
@umbobabo Do you have a screen recording of what this looks like at all? Or a URL which has a large o-table which shows this issue?

**Comment by notlee** [comment]
Here's an example (as posted in #ft-origami) https://www.ft.com/content/762f0c84-d618-11e8-a854-33d6f82e62f8

**Comment by umbobabo** [comment]
Fantastic! Thank you @notlee
