### ISSUE TITLE
Column header baseline alignment

### ISSUE THREAD

**Issue by kavanagh** [Financial-Times/o-table#137]
## What
The header text for a mix of sortable and unsortable columns are not vertically aligned on the same baseline.

## Details
* Notice on Chrome v71
* Expect the column headers to be aligned along the baseline

<img width="605" alt="o-table__basic_demo" src="https://user-images.githubusercontent.com/684559/52061213-bf204b00-2565-11e9-9486-f18ec92da20f.png">

**Comment by notlee** [comment]
Thanks! This is fixed in v7.0.9 (PR: https://github.com/Financial-Times/o-table/pull/138)
