### ISSUE TITLE
Support Server Side rendering

### ISSUE THREAD

**Issue by umbobabo** [Financial-Times/o-table#142]
Feature request.

## What
In some cases, you want to use features like `Responsive Flat` but rendering Server Side.

## Details

We wanted to use the `Responsive Flat` view on AMP importing only the necessary CSS for that kind of view.
We then realised that the `stacked` view implies a transformation converting columns into rows that happens in the Client via the Javascript.

We didn't want to replicate that logic also to avoid misalignment with future releases of o-tables.

I think would good to have the capability to transform the table Server Side. Initially would be sufficient adapt files like this one https://github.com/Financial-Times/o-table/blob/e328db68487255fdc52028ba25faa765f410b471/src/js/Tables/FlatTable.js#L24 to work universally (SS/CS) for the transformation part.

This will also give us a better First Paint in mobile too.

**Comment by ludrob** [comment]
I like this idea, the alternative would be complex and duplicated pieces of logic in the transformers, not good...

**Comment by notlee** [comment]
Hey all 👋 If memory serves correctly this was for AMP and we decided not to use the `responsive flat` version of the table for UX reasons (it could result in very long pages). We decided if we need something like this in the future, `o-table` could provide a CSS class to show the flat style regardless of viewport size and document the markup needed. As it's not needed any longer, closing this for now!
