### ISSUE TITLE
Allow Filtering by Column Value

### ISSUE THREAD

**Issue by GeoffThorpeFT** [Financial-Times/o-table#146]
A Feature request

## What
We make use of o-table as a way of presenting lists to our customers. Some of those lists are fairly long and trigger scrolling. Each customer potentially wants to see a slightly different subset of the data.
If the customers were able to filter the table by values within columns then they could adjust the table into their desired view - without us having to generate lots of customer specific views of the same data.

## Details
Our customers are auditing cookies, tags, and types of infrastructure from both compliance and cost perspectives.  We would like, for example, to send a cookie list to all customer and let each customer filter on the cookies associated with their system.
With filtering in place they would be able to click on the 'system' column with the table and select a system they own. The result would be a reduced table that only showed rows that contained that system.

![unfiltered](https://user-images.githubusercontent.com/11228420/53249819-fa1f2580-36b0-11e9-8b09-196285bb8bba.GIF)
![filter](https://user-images.githubusercontent.com/11228420/53249828-fd1a1600-36b0-11e9-9bb6-8d065053234b.GIF)
![filtered](https://user-images.githubusercontent.com/11228420/53249834-fee3d980-36b0-11e9-9858-b97c1838e56e.GIF)

**Comment by notlee** [comment]
I'm closing this issue as we have now introduced [table filtering](https://github.com/Financial-Times/o-table/#filtering) -- we discussed how the [JS api](https://github.com/Financial-Times/o-table/#filter-imperative) could be used for more advanced usecases.
