### ISSUE TITLE
Table filter (single filter) for editorial 

### ISSUE THREAD

**Issue by MHALE-FT** [Financial-Times/o-table#148]
## What
An update to the table design to include a single filter - instigated by editorial request + instances of the table appearing without a standardised design for including a filter.

## Additional information
For either type of issue:
	- UXD recommendation - Table should include a headline and table functionality should appear to be visually related to, rather than distinct from the table.

![tablefilter](https://user-images.githubusercontent.com/42034079/53636493-5a194d00-3c18-11e9-8843-e3af63229200.png)

https://sketch.cloud/s/Dnz3y/l1jEAz7

**Comment by notlee** [comment]
Just removed the comments `<!--` so your description shows up :)

**Comment by notlee** [comment]
We recently launched [table filtering](https://registry.origami.ft.com/components/o-table@7.3.0#demo-filter) following a beta last month. There is currently a space between the filter select box and its label in [the demo](https://registry.origami.ft.com/components/o-table@7.3.0#demo-filter) but there is a modifier class `.o-forms-title--shrink` being introduced [in the next o-forms major](https://github.com/Financial-Times/o-forms/pull/259/files#diff-177dcef0a5b481c2c87db87f7cdf200dR71). I'll keep this issue open until we update it.

**Comment by notlee** [comment]
> We recently launched [table filtering](https://registry.origami.ft.com/components/o-table@7.3.0#demo-filter) following a beta last month. There is currently a space between the filter select box and its label in [the demo](https://registry.origami.ft.com/components/o-table@7.3.0#demo-filter) but there is a modifier class `.o-forms-title--shrink` being introduced [in the next o-forms major](https://github.com/Financial-Times/o-forms/pull/259/files#diff-177dcef0a5b481c2c87db87f7cdf200dR71). I'll keep this issue open until we update it.

This was completed
