### ISSUE TITLE
Documentation needs improvement

### ISSUE THREAD

**Issue by AniaMakes** [Financial-Times/o-table#177]
I tried to implement Responsive Overflow table. The code snippet demo suggests I need to add classes to the relevant elements. Ditto the snippet which is on github. 
Neither says that for this to work, oTables need to be initialised in the same file that has `this.initPage()`(does this vary? I'm going what's in the project I'm working at) - although initialisation is described later on the page.
The current documentation doesn't mention that the scss file `@include oTable` options needs to contain the relevant one. 

Could the documentation for anything that needs the oTables initialisation + SCSS update to work please be updated accordingly?

**Comment by notlee** [comment]
Thanks for highlighting, this is a good suggestion. Some Origami users use the [Build Service](https://origami.ft.com/docs/services/#build-service) and only need to think about markup, everything else is handled by the Build Service. Maybe a helpful approach would be to add a note under each feature in the markup section along the lines of "include [x] Sass feature and JS if not using the Build Service". Do you feel that would be clear?

**Comment by notlee** [comment]
I've added to the readme which I hope will help point people in the right direction in the future, so I'm going to close this issue. This tutorial might be helpful if you haven't seen it already https://origami.ft.com/docs/tutorials/manual-build/ and also there is more detailed information about initialising component JS here https://origami.ft.com/docs/components/initialising/

If you have any more feedback about our documentation let us know 😊
