### ISSUE TITLE
Responsive tables

### ISSUE THREAD

**Issue by wheresrhys** [Financial-Times/o-table#18]
As requested, here are some examples of responsive tables

- Some interesting scroll based ideas here http://zurb.com/playground/projects/responsive-tables/index.html. Not sure I like it though
- Flex box + pseudo content based solution https://css-tricks.com/responsive-data-tables/. Not sure how unopinionated/reusable it can be
- An overview of a few techniques http://elvery.net/demo/responsive-tables/

**Comment by j-mes** [comment]
@SarahHornsey Could you have a look at the last [link](http://elvery.net/demo/responsive-tables/) in particular with the flipscroll idea. 

I think that could work and be one of the responsive options that product teams can use alongside with the horizontal scrolling from the current version, and the table-less version that I have already created.
