### ISSUE TITLE
Interactivity question

### ISSUE THREAD

**Issue by callumlocke** [Financial-Times/o-table#20]
IG often have a need for interactive features on tables:

- click to sort by column
- type to filter rows

Example at [ft.com/mooc](http://ft.com/mooc)

Would it be a good idea to try and get these features into o-table? Or better to make a new 'interactive table' component built on top of o-table?

**Comment by AlbertoElias** [comment]
Yes, we spoke about this in the last origami meeting. @JakeChampion was going to put in an initial pr with sorting I believe

**Comment by JakeChampion** [comment]
I have code for
> click to sort by column

I don't have code for
> type to filter rows

**Comment by callumlocke** [comment]
Re click-to-sort... We often need to be able to sort values by obscure schemas (not simply taking the td's innerText and sorting alphanumerically). I think the best way is to have an optional data attribute on the `td`, which allows you to override that cell's 'value' for sorting purposes. Something like `data-o-table-order="1"`. Have you got something like that in your code, or would it be easy to add?

type-to-filter is less important for integrating into o-table. It can be bolted on from outside.

**Comment by JakeChampion** [comment]
I believe this can be closed thanks to the latest release -- https://github.com/Financial-Times/o-table/releases/tag/v4.0.0

**Comment by callumlocke** [comment]
Looks good, thanks
