### ISSUE TITLE
Use aria-sort

### ISSUE THREAD

**Issue by wheresrhys** [Financial-Times/o-table#23]
https://www.w3.org/TR/wai-aria/states_and_properties#aria-sort

**Comment by j-mes** [comment]
Writing something more about `aria-sort` to be more useful later on down the pipeline when addressing this issue.

Basically `aria-sort:` has four options. They are `ascending`, `descending`, `none` and `other`. Each one of these are fairly obvious to what they do apart from `other` which can be defined with a custom sort algorithm. 

The caveat with `aria-sort` via the W3 documentation is that **only** one column can have the `aria-sort` markup at a time. If there is a column with an `aria-sort` in place already, then the JavaScript should remove that when it applies the `aria-sort` to another column in the same table.

As for the core experience where JavaScript is not applicable, I am not entirely sure how this would get implemented without DOM manipulation. A possible route would to hardcode the aria-sort into the markup for a pre-determined column and stick with it.

**Comment by AlbertoElias** [comment]
Isn't sorting a feature exclusive to enhanced experience anyway?

**Comment by j-mes** [comment]
Yes it is, and it could be workable on core, only if it sorted one column!

**Comment by onishiweb** [comment]
@JakeChampion this can be closed right?

**Comment by JakeChampion** [comment]
I don't think so, we currently don't have aria-sort in the component

**Comment by onishiweb** [comment]
Ok, should just be the case of adding the `aria-sort` property when the table is sorted. Will leave this open until one of us finds time to add it in.
