### ISSUE TITLE
New o-table style

### ISSUE THREAD

**Issue by SarahHornsey** [Financial-Times/o-table#24]
![table annotations v1](https://cloud.githubusercontent.com/assets/8235225/14636136/abe02350-0621-11e6-8c0e-51e371853016.png)

**Comment by j-mes** [comment]
The technical implementation of the responsive tables can be found at [CodePen](http://codepen.io/j_mes/pen/oxoGpr). I'm currently exploring ways of making it more accessible without using `:before` for the `<td>` when it comes to narrow viewpoints as mentioned in [Accessibility support for CSS generated content](http://tink.uk/accessibility-support-for-css-generated-content/).

I'm looking at the proposal by @onishiweb to use JavaScript instead to insert a different `<th>` when the table is in a narrow viewpoint.

**Comment by j-mes** [comment]
@SarahHornsey I'm looking to implement the graphic changes to `o-table` today as a v4 version, while the work continues on v5. The only thing I can see that might not be in `o-colors` is the background stripe (listed as #FEEBD6 - The closest tint (to my eyes) is red-tint5) which isn't using any of the pink tints. And I think last week that opacity was not to be used for altering the tints that are found in `o-colors`. Which one of the tints would be used for in place of the original one in the image?

**Comment by SarahHornsey** [comment]
@j-mes hi james, can we use warm-1#ffe9d7 instead? thanks

**Comment by j-mes** [comment]
Good choice 👍 . I've nearly finished with this version (Adding a responsive version later).

@SarahHornsey With the small wording part in the `o-table`, would that also apply to the compact version of the table data text colour or just for outside the table?

**Comment by SarahHornsey** [comment]
@j-mes Sorry, I don't understand the question? Do you mean should the small wording show on the compact table?

**Comment by j-mes** [comment]
_(For people following this... this got resolved in the office!)_ 

We are pondering regarding the usage of the small wording, as it would be a new bit inside `o-table` and whenever it would be used enough to merit its inclusion. The example attached to this issue shows it outside the table, but other mockups from product teams shows it inside the heading table cells.

**Comment by j-mes** [comment]
Latest changes can be seen below.

**Before**
![original-preview](https://cloud.githubusercontent.com/assets/5721977/14611451/3042da0e-058a-11e6-9f74-b3bd17945ff6.png)


**After**
![o-table-preview](https://cloud.githubusercontent.com/assets/5721977/14606916/3596d0fe-0577-11e6-9dc6-7ae56c79af7d.png)

**Comment by SarahHornsey** [comment]
@j-mes thanks. Is that Metric Semi-bold or bold in the column heading?

**Comment by SarahHornsey** [comment]
@j-mes can you change the column / row heading to Sans Bold ? thanks!

**Comment by j-mes** [comment]
@SarahHornsey I am not quite sure actually. I will have a look since it's pulling the typography rules from `o-typography`.

**Comment by SarahHornsey** [comment]
@j-mes - Here are the amends, does this make sense?
![artboard 1](https://cloud.githubusercontent.com/assets/8235225/14635623/22318e8e-061f-11e6-977a-922936b2157d.png)

**Comment by SarahHornsey** [comment]
@j-mes thanks, let me know if you are stuck on anything...

![artboard 1](https://cloud.githubusercontent.com/assets/8235225/14635834/0c7032b6-0620-11e6-9421-6b917955293a.png)

**Comment by j-mes** [comment]
Latest version can be seen below:

![typography-change](https://cloud.githubusercontent.com/assets/5721977/14639040/3e72bbb4-0632-11e6-8160-28d175fccbc4.png)

**Comment by j-mes** [comment]
@SarahHornsey Would you mind telling me which colours are assigned to the `primary-data` and `secondary-data` elements in your latest example on the first column please?

**Comment by SarahHornsey** [comment]
@j-mes the primary data is a link and the secondary data is grey-tint4. Also, could the second table column data and header be aligned right, like the others. thanks

**Comment by j-mes** [comment]
The markup of the demo had put the text with the numeric data to align to the right inside the heading column. If someone uses the `o-table` module, they can decide whenever to use text-align: right; on the column headings. The default behaviour for text without the numeric data markup will be aligned to the left inside the heading column.

**Comment by j-mes** [comment]
This has been solved with #26. Closing.
