### ISSUE TITLE
Font weight for tds

### ISSUE THREAD

**Issue by sdbernard** [Financial-Times/o-table#36]
I really think we need to revisit the font-weight on the tables. The light font is starting to break down especially on the compact table. All our web charts use regular weight and I think tables should be no exception.

**Comment by alicebartlett** [comment]
Thanks @sdbernard. Sounds like a job for design, @SarahHornsey are you able to take a look and coordinate with steve?

**Comment by SarahHornsey** [comment]
@sdbernard are you talking about the newly designed tables in Markets Data?

**Comment by sdbernard** [comment]
@SarahHornsey no the tables in the origami components
