### ISSUE TITLE
Sorting numeric columns

### ISSUE THREAD

**Issue by robgodfrey-ft** [Financial-Times/o-table#45]
Hi 

Sorting numeric columns appears to be using a string compare rather than a numeric compare function. For example a single column table with the value 3, 33 and 222  will sort as either 222, 3, 33 (asc) or 33, 3, 222 (desc). Ideally this would sort numerically.

From pastebin:<!DOCTYPE html>
<html lang="en" class="o-hoverable-on ">
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=Edge">
	<title>o-table: responsive-overflow demo</title>
	<meta name="viewport" content="initial-scale=1.0, width=device-width">
	<script src="//cdn.polyfill.io/v2/polyfill.min.js?features=Element.prototype.matches,default"></script>
	<style>body { margin: 0; } .core .o--if-js, .enhanced .o--if-no-js { display: none !important; }</style>
	<script>(function(d) { d.className = d.className + ' demo-js'; })(document.documentElement);</script>
	<link rel="stylesheet" href="//origami-build.ft.com/v2/bundles/css?modules=o-table@5.1.0:/demos/src/demo.scss,o-fonts@^2.0.0">
</head>
<body>
<table class="o-table o-table--responsive-overflow o-table--row-stripes" data-o-component="o-table">
	<thead>
		<th>Cost (GBP)</th>
	</thead>
	<tbody>
		<tr>
			<td>3</td>
		</tr>
		<tr>
			<td>222</td>
		</tr>
		<tr>
			<td>33</td>
		</tr>
	</tbody>
</table>

<script src="//origami-build.ft.com/v2/bundles/js?modules=o-table@5.1.0:/demos/src/demo.js,o-fonts@^2.0.0"></script>
<script src="//registry.origami.ft.com/embedapi?autoload=resize"></script>
</body>
</html>

**Comment by onishiweb** [comment]
Hi @robgodfrey-ft, can you send us a link to the code you're using. Looking at the demos in the registry (http://registry.origami.ft.com/components/o-table) the sorting appears to be working ok with numeric values.

**Comment by robgodfrey-ft** [comment]
I have created a gist: https://gist.github.com/anonymous/9bf5a8f1d43ef55c1aaa812011f5ad83

I think the examples in the o-table demo work as expected is because all the numeric values are the same number of characters (i.e. same length). Once the length starts to vary the sort order is affected, producing unexpected results.

**Comment by onishiweb** [comment]
Thanks for the example @robgodfrey-ft, on your `th` and `td`'s where the data is numeric, you're missing the attributes `data-o-table-data-type="numeric" class="o-table__cell--numeric"` which are required for the JS to work out to sort numerically instead of as a string.

I've tested with your example code and it seems to work fine, you can see these being used in any of our example code in the Registry or JSBin demos.

**Comment by robgodfrey-ft** [comment]
Ok thanks. FYI Looks like the demo for Responsive-Overflow and Responsive-Scroll don't include those attributes on the numeric columns.

**Comment by onishiweb** [comment]
Ah ok thanks, I'll add an issue to update those demos.
