### ISSUE TITLE
Integrate o-tracking to get analytics on table sorting interactions

### ISSUE THREAD

**Issue by joannaskao** [Financial-Times/o-table#59]
Would love to get analytics on how often people sort up/down and on what particular columns they sort on (e.g. record the name of the column along with the direction).

**Comment by rowanmanning** [comment]
Thanks @joannaskao, Lee's going to look at this as part of a larger table overhaul so gonna mark it as blocked for now while we wait for that work to start :)

**Comment by chee** [comment]
Sorry, it's taken so long to get a reply to this!

in the future i think we'd recommend listening to the [o-table events](https://github.com/Financial-Times/o-table/blob/0ac44c97263cb33c5ccc2ed78b78f1efe1982815/src/js/Tables/BaseTable.js#L409-L417) and tracking those from the app!!
