### ISSUE TITLE
Example markup on registry.origami.ft.com is invalid

### ISSUE THREAD

**Issue by dndhm** [Financial-Times/o-table#78]
```
<thead>
  <th>...</th>
  <th>...</th>
...
</thead>
```
is given as example markup for several of the demos, but this is invalid HTML. 

> can contain Zero or more `<tr>` elements.
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/thead

**Comment by notlee** [comment]
Hi @dndhm sorry for the delayed reply. Thanks for bringing this to our attention! I have updated the demos in v6.4.0, it should appear in the registry within an hour.
https://github.com/Financial-Times/o-table/releases/tag/v6.4.0

**Comment by dndhm** [comment]
@notlee No problem - thanks for entertaining my pedantry.

**Comment by notlee** [comment]
I love pedantry. Thanks again :)
