### ISSUE TITLE
We would love a way to specify non-sortable columns

### ISSUE THREAD

**Issue by laurieboyes** [Financial-Times/o-table#80]
E.g. in this case I don't want the checkbox column to be sortable:

![screen shot 2018-02-13 at 10 51 45](https://user-images.githubusercontent.com/4622378/36146988-62036622-10ae-11e8-9f98-4b170e07cb20.png)

**Comment by notlee** [comment]
@laurieboyes `v6.4.0` adds the data attribute `data-o-table-heading-disable-sort`. Apply that to your heading to disable sort 👌 
https://github.com/Financial-Times/o-table#disable-sort-on-one-or-more-columns
