### ISSUE TITLE
Does not sort based on localised characters

### ISSUE THREAD

**Issue by Limess** [Financial-Times/o-table#84]
## Issue
The default sort places localised characters, for example: `Æ`, last in the sorted list.

## Expected
The characters are compared using [`String.prototype.localeCompare`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/localeCompare) rather than direct string comparison to take into account locales.

## Example:
```js
const items = ['Æ', 'café', 'apple', 'caffeine']
items.sort((a, b) => a.localeCompare(b));
// (4) ["Æ", "apple", "café", "caffeine"]
items.sort();
// (4) ["apple", "caffeine", "café", "Æ"]
```

**Comment by notlee** [comment]
Wonderful issue writing 👏
