### ISSUE TITLE
Is there a need for a bordered table?

### ISSUE THREAD

**Issue by rowanmanning** [Financial-Times/o-table#98]
@wheresrhys mentioned a need for this, the current Dewey design has an example:
https://dewey.in.ft.com/runbooks/origami-image-service-v2

@draysonandstock could we have a chat about it?

**Comment by draysonandstock** [comment]
@rowanmanning yes let's discuss. We should have a version for it, even if we just spec a colour and  thickness for any borders.

**Comment by notlee** [comment]
Table rows and borders where updated in v7 with direction from IG: https://github.com/Financial-Times/o-table/pull/108

**Comment by wheresrhys** [comment]
:tada:
